name: XAntiVPN
version: ${version}
main: hu.xavpn.bukkit.XavBukkitPlugin
author: geri_888
description: IPAPI.is based anti VPN/proxy/datacenter checker.
website: https://github.com/geri-888/xav
commands:
  xav:
    description: XAntiVPN commands
    usage: /xav <kivetel|eltavolit|ip|alt|version|reload>
permissions:
  xav.whitelist:
    description: Allows whitelist add/remove commands.
    default: op
  xav.kivetel:
    description: Bypass the anti VPN check on supported platforms.
    default: false
  xav.mod:
    description: Allows IP, ISP and alt lookup commands.
    default: op
  xav.reload:
    description: Allows reloading XAntiVPN config and storage.
    default: op
